# Set verbose level of the control (macro) file
/control/verbose 2

# Set verbose level of the RunManager 
/run/verbose 1

# Set verbose level of the Particle Tracking
/tracking/verbose 0

# Set physics list (
# 1st parameter - list name (FTFP_BERT, QGSP_BERT, QGSC_BERT_EMZ, ...)
# 2nd parameter - use "withOptical" to turn on optical physics 
/physics/selectList FTFP_BERT

# Crystal size along X, Y and Z axis
/detector/setCrystalSize 20 20 400 mm

# Crystal material - currently supported values are:
# PWO-CRYTUR, PWO-SICCAS, PWO-BOGO, PWO-SICCAS-YANG
# CSGlass-0-T, SciGlass-4-1-L, SciGlass-4-1-T, SciGlass-2-2-T, SciGlass-2-1-L, SciGlass-2-1-T, SciGlass-1-1-T 
/detector/setCrystalMaterial SciGlass-4-1-L

# Number of crystals in the assembly along X and Y axis
/detector/setCrystalNumberX 13
/detector/setCrystalNumberY 13

# Wrap material. "C10H8O4" is vm2000. "G4_TEFLON" is teflon. "NONE" is no wrap material
/detector/setWrapMaterial C10H8O4

/detector/usePrimitiveScorer true
/detector/saveEnergyWorldEscape false
/detector/useGlobalScoringMeshes  false
/detector/useUnitVolumeScoringMeshes false

# Detector name                      Diameter   Glass type              Cathode
# "R4125"    or "R1450"              18 mm      borosilicate default    bialkali
# "R1828-01" or "H1949-51"           53 mm      borosilicate            bialkali
# "R2059"    or "H3177"              53 mm      quartz (fused silica)   bialkali
# "R2257"                            52 mm      borosilicate            multialkali
# "S13360-6025CS" 6mm MPPC           6x6 mm     silicone resin          silicon crystal
# "S13360-6025CS-2x2" 2x2 MPPC       12x12 mm   silicone resin          silicon crystal
# "S13360-6025CS-20" 20mm MPPC       20x20 mm   silicone resin          silicon crystal
# "S13360-6025CS-Custom" 2x2 MPPC    20x20 mm   silicone resin          silicon crystal
#  with S14420-3025MG efficiency 
/detector/setDetectorType R4125

# Reflective shield (mostly important for MPPT, default is false)
/detector/setReflectiveShield false

# Set grease type (BC630 or PDMS) 
/detector/setGreaseType BC630

# Set grease thickness (use 0 for no grease) 
/detector/setGreaseThickness 0 mm

#/process/optical/verbose 10

# Control optical processes
#/process/optical/processActivation Cerenkov      true
#/process/optical/processActivation OpAbsorption  false
#/process/optical/processActivation OpBoundary    true
#/process/optical/processActivation Scintillation true
#/process/optical/processActivation OpRayleigh    false
#/process/optical/processActivation OpMieHG       false
#/process/optical/processActivation OpWLS         false

#/process/optical/scintillation/setExcitationRatio .5
#/process/optical/scintillation/setByParticleType false
#/process/optical/scintillation/setTrackInfo      false
#/process/optical/scintillation/setFiniteRiseTime false
#/process/optical/scintillation/setStackPhotons   false

#/process/optical/cerenkov/setMaxPhotons 3
#/process/optical/cerenkov/setMaxBetaChange 10

# Starting with Geant4 version 10.7, it is possible to specify up to three decay time constants, for particle-independent and particle-dependent yields
#/process/optical/scintillation/setEnhancedTimeConstants true
#/process/optical/scintillation/setByParticleType false
#/process/optical/scintillation/setTrackInfo      false
#/process/optical/scintillation/setFiniteRiseTime true
#/process/optical/scintillation/setStackPhotons   true

/run/initialize

/geometry/test/run

# /process/list

# Particle gun (default)
/gps/pos/type Point
/gps/particle e-
/gps/direction 0 0 1
/gps/pos/centre 0 0 -40 mm

# Particle gun (OP, SciGlass4 emission)
# /control/execute macros/gps-sciglass-emission.mac
# /control/execute macros/gps-pwo-emission.mac

/gps/ene/mono 1.5 GeV
/gps/pos/centre 0. 0. -40. mm

#/vis/ASCIITree/verbose 13
#/vis/drawTree

/run/initialize
  
  # List available visualization options
/vis/list
  
  # Use it as a standard default
/vis/open OGL 1000x800-0+0
  #/vis/open OGLI 600x600-0+0
  #/vis/open OGLIX 600x600-0+0
  #/vis/open OGLIQt 1000x800-0+0
  #
  #/vis/open OGLS 600x600-0+0
  #/vis/open OGLSX 600x600-0+0
  #/vis/open OGLIQt 1000x800-0+0
  #/vis/open OGLIQt_FALLBACK 600x600-0+0
  #/vis/open OGLSQt_FALLBACK 600x600-0+0
  
  
  # Use this open statement to create a .prim file suitable for
  # viewing in DAWN:
  #/vis/open DAWNFILE
  
  # Use this open statement to create a .heprep file suitable for
  # viewing in HepRApp:
  #/vis/open HepRepFile
  
  # Use this open statement to create a .wrl file suitable for
  # viewing in a VRML viewer:
  #/vis/open VRML2FILE
  
  # Disable auto refresh and quieten vis messages whilst scene and
  # trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
  #
  # Draw geometry:
/vis/drawVolume
  #
  # Specify view angle:
  #/vis/viewer/set/viewpointThetaPhi  90. 0.
  #/vis/viewer/set/viewpointThetaPhi -90. 0.
  #/vis/viewer/set/viewpointThetaPhi 0. 0.
  #/vis/viewer/set/viewpointThetaPhi 0. 0.
  #/vis/viewer/set/viewpointThetaPhi 90.0000 89.99999999
/vis/viewer/set/viewpointThetaPhi -90.0000 -89.99999999
  #/vis/viewer/set/viewpointThetaPhi -135. -135.
  #
  # Specify zoom value:
  #/vis/viewer/zoom 50.
/vis/viewer/zoom 2.
  
  
  # Draw smooth trajectories at end of event, showing trajectory points
  # as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
  #/vis/modeling/trajectories/create/drawByCharge
  #/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
  #/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
  # (if too many tracks cause core dump => /tracking/storeTrajectory 0)
  #
  #
  # Draw hits at end of event:
/vis/scene/add/hits
  #
  # To draw only gammas:
  # /vis/filtering/trajectories/create/particleFilter
  # /vis/filtering/trajectories/particleFilter-0/add gamma
  #
  # To invert the above, drawing all particles except gammas,
  # keep the above two lines but also add:
  #fsv /vis/filtering/trajectories/particleFilter-0/invert true
  #
  # Many other options are available with /vis/modeling and /vis/filtering.
  # For example, to fSelectCmd colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/list
/vis/modeling/trajectories/drawByParticleID-0/set e- cyan
/vis/modeling/trajectories/drawByParticleID-0/set e+ gray
/vis/modeling/trajectories/drawByParticleID-0/set kaon- magenta
/vis/modeling/trajectories/drawByParticleID-0/set kaon+ magenta
/vis/modeling/trajectories/drawByParticleID-0/set pion+ magenta
/vis/modeling/trajectories/drawByParticleID-0/set pion- magenta
/vis/modeling/trajectories/drawByParticleID-0/set muon- red
/vis/modeling/trajectories/drawByParticleID-0/set muon+ red
/vis/modeling/trajectories/drawByParticleID-0/set pion0 blue
/vis/modeling/trajectories/drawByParticleID-0/set gamma yellow
/vis/modeling/trajectories/drawByParticleID-0/set proton blue
/vis/modeling/trajectories/drawByParticleID-0/set neutron gray
/vis/modeling/trajectories/drawByParticleID-0/set lambda green
  #/vis/modeling/trajectories/drawByParticleID-0/set e- yellow
  #
  # To superimpose all of the events from a given run:
  # /vis/scene/endOfEventAction accumulate
  #
  # Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
  #
  # For file-based drivers, use this to create an empty detector view:
  #/vis/viewer/flush
  #
  #-----------------------------------------------------------------------
  #/control/execute depfet09.mac
  #-----------------------------------------------------------------------
  #/control/execute vtx.mac
/vis/viewer/set/background 1 1 1

/vis/scene/endOfEventAction accumulate 100
  
  #/vis/viewer/set/cutawayMode intersection
/vis/viewer/clearCutawayPlanes

/vis/viewer/addCutawayPlane 0  30  0  cm  0. -500 0
  #/vis/viewer/addCutawayPlane 0  1  0  cm  0. -0.1 0
  #/vis/viewer/addCutawayPlane 0  1  0  cm  0. -500. 1.
  #/vis/viewer/addCutawayPlane 0  1  0  cm  0. 100. 1.
  # XY 
  #/vis/viewer/addCutawayPlane  1  0  0  cm   0  0  -0.001
  #  ZY
  #/vis/viewer/addCutawayPlane 0  1  0  cm  -0.001 0  0
  #/vis/viewer/clearCutawayPlanes
  #/run/initialize
  #/run/beamOn 1
  #--------------CMS vis
  #/vis/viewer/set/viewpointThetaPhi -30. -30.
  #/vis/viewer/zoomTo 100
  
  #========= CMS view =========================
  #/vis/viewer/addCutawayPlane 0 0 7 m 0 0 1
  #/vis/viewer/addCutawayPlane 0 0 7 m 1 0 0
  #/vis/viewer/addCutawayPlane 0 0 7 m 0 -1 0
  #/vis/viewer/set/style surface
  #/vis/viewer/colourByDensity 1 g/cm3 .5 3 10
  #---------------------------------------------------
  # /vis/viewer/zoom 0.5
/vis/viewer/set/viewpointThetaPhi -90 -45 deg
/vis/viewer/zoom 70
  
  
  
  # 1000 optical photons, 10000 times
/run/beamOn 1

# Draw energy deposition projections 
# /score/drawProjection crystalsMesh eDepCrystals allCrystalsColorMap
# /score/drawProjection pmtsMesh eDepPmts allCrystalsColorMap
# /score/drawProjection crystalMesh1 eDepCrystal1 centerCrystalColorMap
# /score/drawProjection ...
