# Set verbose level of the control (macro) file
/control/verbose 2

# Set verbose level of the RunManager 
/run/verbose 1

# Set verbose level of the Particle Tracking
/tracking/verbose 0

# Set physics list (
# 1st parameter - list name (FTFP_BERT, QGSP_BERT, QGSC_BERT_EMZ, ...)
# 2nd parameter - use "withOptical" to turn on optical physics 
/physics/selectList FTFP_BERT withOptical

# Crystal size along X, Y and Z axis
/detector/setCrystalSize 20 20 400 mm

# Crystal material - currently supported values are:
# PWO-CRYTUR, PWO-SICCAS, PWO-BOGO, PWO-SICCAS-YANG
# CSGlass-0-T, SciGlass-4-1-L, SciGlass-4-1-T, SciGlass-2-2-T, SciGlass-2-1-L, SciGlass-2-1-T, SciGlass-1-1-T 
/detector/setCrystalMaterial PWO-CRYTUR

# Number of crystals in the assembly along X and Y axis
/detector/setCrystalNumberX 1
/detector/setCrystalNumberY 1

# Wrap material. "C10H8O4" is vm2000. "G4_TEFLON" is teflon. "NONE" is no wrap material
/detector/setWrapMaterial C10H8O4

/detector/usePrimitiveScorer false
/detector/saveEnergyWorldEscape false
/detector/useGlobalScoringMeshes  false
/detector/useUnitVolumeScoringMeshes false

# Detector name                      Diameter   Glass type              Cathode
# "R4125"    or "R1450"              18 mm      borosilicate default    bialkali
# "R1828-01" or "H1949-51"           53 mm      borosilicate            bialkali
# "R2059"    or "H3177"              53 mm      quartz (fused silica)   bialkali
# "R2257"                            52 mm      borosilicate            multialkali
# "S13360-6025CS" 6mm MPPC           6x6 mm     silicone resin          silicon crystal
# "S13360-6025CS-2x2" 2x2 MPPC       12x12 mm   silicone resin          silicon crystal
# "S13360-6025CS-20" 20mm MPPC       20x20 mm   silicone resin          silicon crystal
# "S13360-6025CS-Custom" 2x2 MPPC    20x20 mm   silicone resin          silicon crystal
#  with S14420-3025MG efficiency 
/detector/setDetectorType R4125

# Reflective shield (mostly important for MPPT, default is false)
/detector/setReflectiveShield false

# Set grease type (BC630 or PDMS) 
/detector/setGreaseType BC630

# Set grease thickness (use 0 for no grease) 
/detector/setGreaseThickness 0 mm

/run/initialize

/geometry/test/run

# Particle gun (default)
/control/execute macros/gps-default.mac
/gps/ene/mono 10 MeV

# Particle gun (OP, SciGlass4 emission)
# /control/execute macros/gps-sciglass-emission.mac
# /control/execute macros/gps-pwo-emission.mac
/gps/pos/centre 0. 0. -40. mm

/vis/ASCIITree/verbose 13
/vis/drawTree

# 1000 optical photons, 10000 times
/run/beamOn 1000

# Draw energy deposition projections 
# /score/drawProjection crystalsMesh eDepCrystals allCrystalsColorMap
# /score/drawProjection pmtsMesh eDepPmts allCrystalsColorMap
# /score/drawProjection crystalMesh1 eDepCrystal1 centerCrystalColorMap
# /score/drawProjection ...
